//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CcExcel.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CcExcel.Messages.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheet.
        /// </summary>
        internal static string DefaultSheetName {
            get {
                return ResourceManager.GetString("DefaultSheetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple sheets with same name or same id were found..
        /// </summary>
        internal static string MultipleSheetsWithSameNameOrSameIdWereFound {
            get {
                return ResourceManager.GetString("MultipleSheetsWithSameNameOrSameIdWereFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The excel file is probably corrupted..
        /// </summary>
        internal static string TheExcelFileIsProbablyCorrupted {
            get {
                return ResourceManager.GetString("TheExcelFileIsProbablyCorrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter cellReference was not in a correct format..
        /// </summary>
        internal static string TheParameterCellReferenceWasNotInACorrectFormat {
            get {
                return ResourceManager.GetString("TheParameterCellReferenceWasNotInACorrectFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; cannot be converted in {1}..
        /// </summary>
        internal static string TheValue0CannotBeConvertedIn1 {
            get {
                return ResourceManager.GetString("TheValue0CannotBeConvertedIn1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The worksheetPart was not found..
        /// </summary>
        internal static string TheWorksheetPartWasNotFound {
            get {
                return ResourceManager.GetString("TheWorksheetPartWasNotFound", resourceCulture);
            }
        }
    }
}
